### ISSUE TITLE
AVOUM Tracker

### ISSUE THREAD

**Issue by kwannoel** [kwannoel/ckb#1]
## TODO

- [ ] Purge fixmes / todos
- [ ] Cell data format for account id should be first 32 bytes of data.
- [ ] Update local dependencies to point to github repositories, see: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations

## Future
- [ ] I was wondering what's the necessity of a rebase script in the first place.
I was thinking that we could just swap outdated account cells with the latest ones, with the miner resubmitting a transaction with these latest inputs.
I realized this doesn't work because you would need the original submitter to re-sign this new transaction.
With the rebase script, signing and submission doesn't need to be done again.
But this makes me wonder if we should bundle the script as part of the transaction when signing, 
so that there's evidence a particular rebase script was used. 
noel

Even if that is needed though, maybe in the production run of AVOUM for Nervos we will do it. Don't think this is necessary for the PoC.
- [ ] Include the account id, even before we lock in the first transaction,
  to ensure that we can find txs.
- [ ] In the future, for remote txs,
  as part of the sync protocol, we probably need to broadcast to all neighbouring nodes to ask for latest states.
  Reason being, if a account tx comes in,
  we are unsure that any of our past transactions were malleable txs,
  and which of these are the account we are looking for.
  So we should probably have some sort of broadcast mechanism to let other nodes know which are these,
  and trace further if necessary?
  Or maybe we should completely NOT trace, and just rely on sync.
  Yeah we probably don't need this now... We can use bloom filters.
  Check if cell is live in the first place.
  Nodes need to efficiently somehow do so.
- [ ] Purge the entry from the map, if we successfully rebase.

**Comment by kwannoel** [comment]
Don't need to sign rebase, since **rebased tx** itself is valid.

**Comment by kwannoel** [comment]
fix rustc warnings too
